### ISSUE TITLE
JavaScript error while prerendering - phantom-page-render

### ISSUE THREAD

**Issue by JohnRSim** [chrisvfritz/prerender-spa-plugin#150]
if I change the assetsPublicPath to root ie

```javascript
module.exports = {
  build: {
    env: require('./prod.env'),
    index: path.resolve(__dirname, '../dist/index.html'),
    assetsRoot: path.resolve(__dirname, '../dist'),
    assetsSubDirectory: 'static',
    assetsPublicPath: '/',
```
Within /config/index.js
I get the following error

```
\node_modules\prerender-spa-plugin\lib\compile-to-html.js:82
                    if (error) throw stdout
                               ^
WARNING: JavaScript error while prerendering: /about/press
TypeError: undefined is not an object (evaluating 'e[r].call')

  phantomjs://code/phantom-page-render.js:26 in onError

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! website@2.2.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the website@2.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xx\AppData\Roaming\npm-cache\_logs\2018-01-30T16_51_06_156Z-debug.log
```

but if I add a child folder doesn't matter whatever
```javascript
    assetsPublicPath: '/MYEXAMPLEFOLDER/',
````

Then it works fine.. 
but Id like the site to load up from root - not a child folder.. 

```
    "prerender-spa-plugin": "^2.1.0",
```

Log file
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.3.0
3 info using node@v8.4.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle website@2.2.0~prebuild: website@2.2.0
6 info lifecycle website@2.2.0~build: website@2.2.0
7 verbose lifecycle website@2.2.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle website@2.2.0~build: PATH: C:\Users\xx\AppData\Roaming\nvm\v8.4.0\node_modules\npm\bin\node-gyp-bin;C:\work\web\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Bitvise SSH Client;C:\Users\xx\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\xx\AppData\Local\Microsoft\WindowsApps;C:\Users\xx\AppData\Local\atom\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\xx\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\xx\AppData\Local\Microsoft\WindowsApps;
9 verbose lifecycle website@2.2.0~build: CWD: C:\work\web
10 silly lifecycle website@2.2.0~build: Args: [ '/d /s /c', 'node build/build.js' ]
11 silly lifecycle website@2.2.0~build: Returned: code: 1  signal: null
12 info lifecycle website@2.2.0~build: Failed to exec build script
13 verbose stack Error: website@2.2.0 build: `node build/build.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\xx\AppData\Roaming\nvm\v8.4.0\node_modules\npm\lib\utils\lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\xx\AppData\Roaming\nvm\v8.4.0\node_modules\npm\lib\utils\spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid website@2.2.0
15 verbose cwd C:\work\web
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v8.4.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error website@2.2.0 build: `node build/build.js`
22 error Exit status 1
23 error Failed at the website@2.2.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by JohnRSim** [comment]
Swapped to V3 branch and all works fine.
