### ISSUE TITLE
Compile to HTML throws error (PhantomJS)

### ISSUE THREAD

**Issue by Loschcode** [chrisvfritz/prerender-spa-plugin#161]
I'm trying to include this plugin into an existing project. In the prod configuration I added

```
new PrerenderSpaPlugin(
  // Absolute path to compiled SPA
  path.join(__dirname, '../dist'),
  // List of routes to prerender
  ['/coins']
),
```

I then try to `npm run build` and it crashes like so

```

⠸ building for production.../Users/loschcode/Desktop/work/projects/bloodbath/app/node_modules/prerender-spa-plugin/lib/compile-to-html.js:82
                    if (error) throw error
                               ^

Error: Command failed: /usr/local/lib/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs /Users/loschcode/Desktop/work/projects/bloodbath/app/node_modules/prerender-spa-plugin/lib/phantom-page-render.js http://localhost:8001/coins {}

    at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bloodbath-app@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
```

I investigated the file and it looks like PhantomJS crashes for some reason, but it's hard to be sure, what could be the reason of this problem ?

PS : The only similar issue I spotted on the Internet is in Chinese and was posted a few days ago, maybe a problem linked some changes in a package ?

**Comment by Tribex** [comment]
@Loschcode Just out of curiosity, what happens when you try to run the binary yourself? `/usr/local/lib/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs`
I have had similar issues on Linux due to phantomjs-prebuilt not being properly installed.

By the way, I'd recommend using the v3 branch of this project (It uses puppeteer instead of PhantomJS), which will be transitioning from beta to a full release in the coming days. `npm i prerender-spa-plugin@next --save-dev`

**Comment by Loschcode** [comment]
When I run `/usr/local/lib/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs` it just launches the phantomjs console ...

Anyway I tried your command and to deploy on Dokku again and this time it shows this

```
remote: [prerender-spa-plugin] You appear to be using the v2 argument-based configuration options. It's recommended that you migrate to the clearer object-based configuration system.
remote: Check the documentation for more information.
remote: /tmp/build/node_modules/prerender-spa-plugin/es6/index.js:26
remote:     staticDir ? this._options.staticDir = staticDir : null
remote:                                         ^
remote:
remote: TypeError: Cannot set property 'staticDir' of undefined
```

Getting close ...

**Comment by Tribex** [comment]
Ooh, that might be a bug. I'll take a look today.

**Comment by Loschcode** [comment]
By the way, I'm curious, why are you getting rid of PhantomJS ?

**Comment by Tribex** [comment]
It hasn't kept up the pace with modern web development, and is known to have issues installing properly. I actually can't get it working on my system. (At least so far.)

Might as well use a browser that more closely resembles that of your users. :)

**Comment by Tribex** [comment]
Should be fixed in `prerender-spa-plugin 3.0.0-beta.2` :)

**Comment by Loschcode** [comment]
Thanks for this fix, it did the work for this part but now it crashes right after, I don't know anything about puppeteer but maybe I just have to do something from my side ?

```
remote: [prerender-spa-plugin] You appear to be using the v2 argument-based configuration options. It's recommended that you migrate to the clearer object-based configuration system.
remote: Check the documentation for more information.
remote: Error: Failed to launch chrome!
remote: /tmp/build/node_modules/puppeteer/.local-chromium/linux-543305/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
remote:
remote:
remote: TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
remote:
remote:     at onClose (/tmp/build/node_modules/puppeteer/lib/Launcher.js:246:14)
remote:     at Interface.helper.addEventListener (/tmp/build/node_modules/puppeteer/lib/Launcher.js:235:50)
remote:     at Interface.emit (events.js:185:15)
remote:     at Interface.close (readline.js:379:8)
remote:     at Socket.onend (readline.js:152:10)
remote:     at Socket.emit (events.js:185:15)
remote:     at endReadableNT (_stream_readable.js:1101:12)
remote:     at process._tickCallback (internal/process/next_tick.js:114:19)
remote: [Prerenderer - PuppeteerRenderer] Unable to start Puppeteer
remote: (node:441) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'close' of null
remote:     at PuppeteerRenderer.destroy (/tmp/build/node_modules/@prerenderer/renderer-puppeteer/es6/renderer.js:142:21)
remote:     at Prerenderer.destroy (/tmp/build/node_modules/@prerenderer/prerenderer/es6/index.js:87:20)
remote:     at PrerendererInstance.initialize.then.then.then.then.then.then.catch.err (/tmp/build/node_modules/prerender-spa-plugin/es6/index.js:118:27)
remote:     at <anonymous>
remote:     at process._tickCallback (internal/process/next_tick.js:118:7)
remote: (node:441) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
remote: (node:441) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'll try to investigate on my end this one, but that's just weird

**Comment by Tribex** [comment]
@Loschcode Perhaps the [official puppeteer docker guide](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker) might help?
