### ISSUE TITLE
Warnings on a vue app with prerendering

### ISSUE THREAD

**Issue by Berkmann18** [chrisvfritz/prerender-spa-plugin#226]
I've been following a [video](https://www.youtube.com/watch?v=pwHdFPEX4NA) where the guy was using this package for prerendering the Vue components and I've noticed the warning saying that I should use `postProcess` instead of `postProcessHTML` which I did but despite that, I still get some warnings which I'm clueless about when trying to solve them, here's what I get:

```bash
> cross-env NODE_ENV=production webpack --progress --hide-modules

[prerender-spa-plugin] You appear to be using the v2 argument-based configuration options. It's recommended that you migrate to the clearer object-based configuration system.
Check the documentation for more information.
 95% emitting[prerender-spa-plugin] Unable to prerender all routes!                  
(node:12610) UnhandledPromiseRejectionWarning: Error: [prerender-spa-plugin] Rendered routes are empty, did you forget to return the `context` object in postProcess?
    at PrerendererInstance.initialize.then.then.then.then.renderedRoutes (/home/maxie/Dropbox/Public/Learning/VueJS/vue-static/node_modules/prerender-spa-plugin/es6/index.js:91:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:12610) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12610) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Here's my `webpack.config.js`:
```js
var path = require('path')
var webpack = require('webpack')
var PrerenderSpaPlugin = require('prerender-spa-plugin')
var HtmlWebpackPlugin = require('html-webpack-plugin')

module.exports = {
  entry: './src/main.js',
  output: {
    path: path.resolve(__dirname, './dist'),
    publicPath: '/',
    filename: 'build.js'
  },
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          'vue-style-loader',
          'css-loader'
        ],
      },      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          loaders: {
          }
          // other vue-loader options go here
        }
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/
      },
      {
        test: /\.(png|jpg|gif|svg)$/,
        loader: 'file-loader',
        options: {
          name: '[name].[ext]?[hash]'
        }
      }
    ]
  },
  resolve: {
    alias: {
      'vue$': 'vue/dist/vue.esm.js'
    },
    extensions: ['*', '.js', '.vue', '.json']
  },
  devServer: {
    historyApiFallback: true,
    noInfo: true,
    overlay: true
  },
  performance: {
    hints: false
  },
  devtool: '#eval-source-map'
}

if (process.env.NODE_ENV === 'production') {
  module.exports.devtool = '#source-map'
  // http://vue-loader.vuejs.org/en/workflow/production.html
  module.exports.plugins = (module.exports.plugins || []).concat([
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: '"production"'
      }
    }),
    new HtmlWebpackPlugin({
      template: 'index.html',
      filename: path.resolve(__dirname, 'dist/index.html')
    }),
    new PrerenderSpaPlugin(
      // Absolute path to compiled SPA
      path.resolve(__dirname, './dist'),
      // List of routes to prerender
      [ '/', '/about', '/contact' ], {
        // Options
        postProcess(context) {
          let titles = {
            '/': 'My home page',
            '/about': 'My awesome about page',
            '/contact': 'Contact me'
          };
          return context.html.replace(
            /<title>[^<]*<\/title>/i,
            `<title>${titles[context.route]}</title>`
          )
        }
      }
    ),
    new webpack.optimize.UglifyJsPlugin({
      sourceMap: true,
      compress: {
        warnings: false
      }
    }),
    new webpack.LoaderOptionsPlugin({
      minimize: true
    })
  ])
}

```
I was thinking of going back to the way used in the video but it seems deprecated.

**Comment by Tribex** [comment]
Try this configuration. You're still using the old v2 style config:

```js
    new PrerenderSpaPlugin({
      // Absolute path to compiled SPA
      staticDir: path.resolve(__dirname, './dist'),
      // List of routes to prerender
      routes: [ '/', '/about', '/contact' ],
      // Options
      postProcess(context) {
        let titles = {
          '/': 'My home page',
          '/about': 'My awesome about page',
          '/contact': 'Contact me'
        };
        context.html = context.html.replace(
          /<title>[^<]*<\/title>/i,
          `<title>${titles[context.route]}</title>`
        )
        return context
      }
    }),
```

**Comment by Berkmann18** [comment]
@Tribex What you wrote is identical to what I have for this package.
Are you sure you wrote the correct new one?

**Comment by Berkmann18** [comment]
Ooh, I see, my bad.
