### ISSUE TITLE
ERROR in [prerender-spa-plugin] Unable to prerender all routes!

### ISSUE THREAD

**Issue by chentianyuan** [chrisvfritz/prerender-spa-plugin#256]
```
[prerender-spa-plugin] Unable to prerender all routes!
TypeError: Cannot read property 'mkdirp' of null
    at Promise (/Users/apple/code/companyProject/local-wy-static/node_modules/prerender-spa-plugin/es6/index.js:61:18)
    at new Promise (<anonymous>)
    at mkdirp (/Users/apple/code/companyProject/local-wy-static/node_modules/prerender-spa-plugin/es6/index.js:60:12)
    at Promise.all.processedRoutes.map.processedRoute (/Users/apple/code/companyProject/local-wy-static/node_modules/prerender-spa-plugin/es6/index.js:125:18)
    at Array.map (<anonymous>)
    at PrerendererInstance.initialize.then.then.then.then.then.then.then.processedRoutes (/Users/apple/code/companyProject/local-wy-static/node_modules/prerender-spa-plugin/es6/index.js:124:54)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
i found that my `compiler.outputFileSystem` is null ... ???

**Comment by Tribex** [comment]
@chentianyuan This means you're using a version of webpack older than 3.x. You'll want to upgrade Webpack.

**Comment by chentianyuan** [comment]
@Tribex thx，you are right ，i fixed it by modified webpack1.12 source code
