### ISSUE TITLE
error when npm run build in Dockerfile

### ISSUE THREAD

**Issue by CrystalXuLi** [chrisvfritz/prerender-spa-plugin#288]
Hi, on my windows PC, it's all right when running npm run build, but when built by Dockerfile on linux, I got this error
```
-  Building for production...
{ Error: spawn E2BIG
    at ChildProcess.spawn (internal/child_process.js:358:11)
    at Object.spawn (child_process.js:533:9)
    at Launcher.launch (/app/node_modules/puppeteer/lib/Launcher.js:122:40) errno: 'E2BIG', code: 'E2BIG', syscall: 'spawn' }
[Prerenderer - PuppeteerRenderer] Unable to start Puppeteer
(node:28) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'close' of null
    at PuppeteerRenderer.destroy (/app/node_modules/@prerenderer/renderer-puppeteer/es6/renderer.js:140:21)
    at Prerenderer.destroy (/app/node_modules/@prerenderer/prerenderer/es6/index.js:87:20)
    at PrerendererInstance.initialize.then.then.then.then.then.then.then.then.catch.err (/app/node_modules/prerender-spa-plugin/es6/index.js:144:29)
(node:28) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Here's my Dockerfile
```Dockerfile
FROM node:latest

RUN apt-get update && \
    apt-get -y install xvfb gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 \
      libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 \
      libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 \
      libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 \
      libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget && \
    rm -rf /var/lib/apt/lists/*


COPY . /app/

WORKDIR app

RUN npm install
RUN npm run build
```
docker build goes well when I'm not using this plugin, I don't know the error comes from this plugin or the puppeteer, waiting for help !

**Comment by Tribex** [comment]
@CrystalXuLi It can be a pain to get this running under Docker. See the puppeteer docs: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch

**Comment by victormafe18** [comment]
No way on getting this working, i dont know what does puppeteer's docs have to do with this, but can you explain me how should i fix that error? I need it for one of my bachelor's subject, thank you in advance.
