### ISSUE TITLE
npm run build, error Failed to lauch chrome. why?

### ISSUE THREAD

**Issue by youjunzai** [chrisvfritz/prerender-spa-plugin#289]
Error: Failed to launch chrome!
/opt/haodou/jenkins/workspace/mvue/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: error while loading shared libraries: libXcursor.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/opt/haodou/jenkins/workspace/mvue/node_modules/puppeteer/node6/lib/Launcher.js:420:14)
    at Interface.helper.addEventListener (/opt/haodou/jenkins/workspace/mvue/node_modules/puppeteer/node6/lib/Launcher.js:409:50)
    at emitNone (events.js:91:20)
    at Interface.emit (events.js:185:7)
    at Interface.close (readline.js:319:8)
    at Socket.onend (readline.js:108:10)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:978:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[Prerenderer - PuppeteerRenderer] Unable to start Puppeteer
(node:3712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'close' of null

**Comment by tduval** [comment]
You're missing some libraries on your system.
This is Puppeteer specific issue, you'll need to install all of theses dependencies to gets things working (on Ubuntu) : 
`sudo apt-get install gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget`

**Comment by Timibadass** [comment]
@tduval @Tribex  , how do fix this issue on windows?

**Comment by Tribex** [comment]
@Timibadass Do you have any more details on your problem? On Windows this issue would not occur.

**Comment by Timibadass** [comment]
@Tribex here's the exact error message i'm getting 
`Chromium revision is not downloaded. Run "npm install" or "yarn install"
    at Launcher.launch (c:\Timi\ajuwaya\node_modules\puppeteer\lib\Launcher.js:118:15)
    at <anonymous>
[Prerenderer - PuppeteerRenderer] Unable to start Puppeteer
(node:11484) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'close' of null`

**Comment by Tribex** [comment]
Try `npm rebuild puppeteer`

**Comment by htfranek** [comment]
Has anyone found a solution for this? OP? "npm rebuild puppeteer" doesn't do it for me.
