### ISSUE TITLE
there is an error about "Chrome revision guarantee work is r662092" after the build

### ISSUE THREAD

**Issue by yehuzi** [chrisvfritz/prerender-spa-plugin#324]
hi, there
I got a terminal error message when i build my project, the message below : 

```
> vue-cli-service build


-  Building for production...
{ TimeoutError: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r662092
    at Timeout.onTimeout (E:\github\DeGao-FrontEnd\node_modules\puppeteer\lib\Launcher.js:353:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) name: 'TimeoutError' }
[Prerenderer - PuppeteerRenderer] Unable to start Puppeteer
(node:940) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'close' of null
    at PuppeteerRenderer.destroy (E:\github\DeGao-FrontEnd\node_modules\@prerenderer\renderer-puppeteer\es6\renderer.js:140:21)
    at Prerenderer.destroy (E:\github\DeGao-FrontEnd\node_modules\@prerenderer\prerenderer\es6\index.js:87:20)
    at PrerendererInstance.initialize.then.then.then.then.then.then.then.then.catch.err (E:\github\DeGao-FrontEnd\node_modules\prerender-spa-plugin\es6\index.js:144:29)
(node:940) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:940) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

development environment is `Vue 3.0`, here is `vue.config.js` file:
```
const PrerenderSPAPlugin = require("prerender-spa-plugin");
const Renderer = PrerenderSPAPlugin.PuppeteerRenderer;
const path = require("path");
module.exports = {
  configureWebpack: config => {
    if (process.env.NODE_ENV !== "production") return;
    return {
      plugins: [
        new PrerenderSPAPlugin({
          staticDir: path.join(__dirname, "dist"),
          routes: ["/", "/products", "/about"],
          renderer: new Renderer({
            inject: {
              foo: "bar"
            },
            headless: true,
            renderAfterDocumentEvent: "render-event"
          })
        })
      ]
    };
  }
};
``` 

i search the Issues, but there is nothing can help me, i can not figure out this problom, can someone help？thanks!!!

**Comment by yehuzi** [comment]
temporarily resolved
