### ISSUE TITLE
build failed, TypeError: Bad argument?

### ISSUE THREAD

**Issue by chenweihan** [chrisvfritz/prerender-spa-plugin#35]
test on Mac  
node v6.2.0
npm v3.8.9

internal/child_process.js:278
  var err = this._handle.spawn(options);
                         ^

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:278:26)
    at exports.spawn (child_process.js:372:9)
    at Object.exports.execFile (child_process.js:139:15)
    at capturePage (/app/www/prerender-spa-plugin/examples/generic-simple/node_modules/prerender-spa-plugin/lib/compile-to-html.js:70:26)
    at /app/www/prerender-spa-plugin/examples/generic-simple/node_modules/prerender-spa-plugin/lib/compile-to-html.js:89:11
    at _invoke (/app/www/prerender-spa-plugin/examples/generic-simple/node_modules/hapi/lib/server.js:305:20)
    at internals.Server._invoke (/app/www/prerender-spa-plugin/examples/generic-simple/node_modules/hapi/lib/server.js:375:16)
    at Items.serial (/app/www/prerender-spa-plugin/examples/generic-simple/node_modules/hapi/lib/server.js:297:14)
    at done (/app/www/prerender-spa-plugin/examples/generic-simple/node_modules/hapMacBook-Pro-2:gen

**Comment by chenweihan** [comment]
I have been solved, is caused by NPM.

**Comment by leenty** [comment]
@chenweihan 我也遇到了与你一样的问题，你是怎么解决的？指导一下我，感激不尽

**Comment by chenweihan** [comment]
you will remove the NPM package and  reinstall again？

**Comment by leenty** [comment]
I temporarily installed a low version to solve this problem,
And it seems to be a problem with the installation of PhantomJS.

**Comment by WebCodeFarmer** [comment]
我也也到了这样的问题，试了手动下载，然后配置环境变量，但是还是不行
