### ISSUE TITLE
chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by shijiezhou1** [chrisvfritz/prerender-spa-plugin#426]
Does any one fix this problem? 

I'm deploying my app tho the bitbucket pipelines and it seems not working at all. 

```
-  Building for production...
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
Error: Failed to launch chrome!
/app/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/app/node_modules/puppeteer/lib/Launcher.js:348:14)
    at Interface.<anonymous> (/app/node_modules/puppeteer/lib/Launcher.js:337:50)
    at Interface.emit (events.js:327:22)
    at Interface.close (readline.js:416:8)
    at Socket.onend (readline.js:194:10)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[Prerenderer - PuppeteerRenderer] Unable to start Puppeteer
(node:19) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'close' of null
    at PuppeteerRenderer.destroy (/app/node_modules/@prerenderer/renderer-puppeteer/es6/renderer.js:140:21)
    at Prerenderer.destroy (/app/node_modules/@prerenderer/prerenderer/es6/index.js:87:20)
    at /app/node_modules/prerender-spa-plugin/es6/index.js:144:29
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by SangilYun** [comment]
I'm having exactly the same error. Do you have any update?

**Comment by gexin1** [comment]
I upgraded puppeteer to the latest
It looks good
i release a package [prerender-spa-plugin-fix](https://www.npmjs.com/package/prerender-spa-plugin-fix)

**Comment by prlcloud** [comment]
I also encountered the same problem, but the deployment failed after updating the package. How did the great God solve it

> I upgraded puppeteer to the latest It looks good i release a package [prerender-spa-plugin-fix](https://www.npmjs.com/package/prerender-spa-plugin-fix)
I also encountered the same problem, but the deployment failed after updating the package. How did the great God solve it

**Comment by gexin1** [comment]
> I also encountered the same problem, but the deployment failed after updating the package. How did the great God solve it
> 
> > I upgraded puppeteer to the latest It looks good i release a package [prerender-spa-plugin-fix](https://www.npmjs.com/package/prerender-spa-plugin-fix)
> > I also encountered the same problem, but the deployment failed after updating the package. How did the great God solve it
You can try
```javascript
// const PrerenderSPAPlugin = require("prerender-spa-plugin");
const PrerenderSPAPlugin = require("prerender-spa-plugin-fix");
```
If this can't solve your problem, I don't know how to solve it
