### ISSUE TITLE
Puppeteer Issues on Oracle Linux 8

### ISSUE THREAD

**Issue by NobUwU** [chrisvfritz/prerender-spa-plugin#454]
Hiya, I am sorta new to linux so this may be a very dumb question but I am unable to build on Oracle Linux 8.

My config is simply:
```js
new PrerenderSPAPlugin({
      staticDir: path.join(__dirname, 'dist'),
      routes: ['/'],
    }),
```
and I am getting this error 

```log
Error: Failed to launch chrome!
/home/opc/project/web/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: /home/opc/project/web/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: cannot execute binary file


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/opc/project/web/node_modules/puppeteer/lib/Launcher.js:348:14)
    at Interface.<anonymous> (/home/opc/project/web/node_modules/puppeteer/lib/Launcher.js:337:50)
    at Interface.emit (node:events:406:35)
    at Interface.close (node:readline:586:8)
    at Socket.onend (node:readline:277:10)
    at Socket.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1329:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[Prerenderer - PuppeteerRenderer] Unable to start Puppeteer
/home/opc/project/web/node_modules/@prerenderer/renderer-puppeteer/es6/renderer.js:140
    this._puppeteer.close()
                    ^

TypeError: Cannot read property 'close' of null
    at PuppeteerRenderer.destroy (/home/opc/project/web/node_modules/@prerenderer/renderer-puppeteer/es6/renderer.js:140:21)
    at Prerenderer.destroy (/home/opc/project/web/node_modules/@prerenderer/prerenderer/es6/index.js:87:20)
    at /home/opc/project/web/node_modules/prerender-spa-plugin/es6/index.js:144:29
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

What I Have Tried

- Going to https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md and doing the fix for centos as Oracle Linux is apparently based on it. 
Whenever I do so I get this error
```log
Error: Unable to find a match: cup-libs
```

**Comment by musakanneh** [comment]
npm install puppeteer  - this should work!
