### ISSUE TITLE
throw new TypeError('"file" argument must be a non-empty string') after update

### ISSUE THREAD

**Issue by alanaasmaa** [chrisvfritz/prerender-spa-plugin#88]
Hello,

I updated my plugins and started to get this. Everything works wihtout prerenderer.

```
child_process.js:380
    throw new TypeError('"file" argument must be a non-empty string');
    ^

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:380:11)
    at exports.spawn (child_process.js:487:38)
    at Object.exports.execFile (child_process.js:208:15)
    at capturePage (C:\Users\AlanAasmaa\Code\project\node_modules\prerender-spa-plugin\lib\compile-to-html.js:72:26)
    at C:\Users\AlanAasmaa\Code\project\node_modules\prerender-spa-plugin\lib\compile-to-html.js:91:11
    at _invoke (C:\Users\AlanAasmaa\Code\project\node_modules\hapi\lib\server.js:305:20)
    at module.exports.internals.Server.internals.Server._invoke (C:\Users\AlanAasmaa\Code\project\node_modules\hapi\lib\server.js:375:16)
    at Items.serial (C:\Users\AlanAasmaa\Code\project\node_modules\hapi\lib\server.js:297:14)
    at done (C:\Users\AlanAasmaa\Code\project\node_modules\hapi\node_modules\items\lib\index.js:31:25)
    at Server.finalize (C:\Users\AlanAasmaa\Code\project\node_modules\hapi\lib\connection.js:171:9)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at Server.emit (events.js:207:7)
    at emitListeningNT (net.js:1346:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the project@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

My spa conf 
```
new PrerenderSpaPlugin(
      path.join(__dirname, '../dist'),
      ['/']
    )
```

**Comment by alanaasmaa** [comment]
This always happends to me, when i open the issue i will fix it :D

The issue was with phantomjs-prebuild -> npm rebuild -> success !!

**Comment by drewlustro** [comment]
thanks @alanaasmaa !

**Comment by Verazzr** [comment]
what means phantomjs-prebuild? help me~

**Comment by alanaasmaa** [comment]
@Verazzr i think i meant `npm install phantomjs-prebuilt` cause npm is not installing peer depeancies anymore
